services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=user2
      - POSTGRES_PASSWORD=1
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/src
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

volumes:
  postgres_data:
