# Generated by Django 3.2.7 on 2023-04-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Brand')),
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Gender')),
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Season')),
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=55)),
                ('in_stock', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.gender')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.season')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
