# Generated by Django 3.2.7 on 2023-05-04 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.season'),
        ),
    ]
